from django.db import models

class Recipe(models.Model):
    name = models.CharField(max_length=200)
    cook_minutes = models.PositiveIntegerField(default=30)
    # area = models.CharField(max_length=200, blank=True)
    # category = models.CharField(max_length=200, blank=True)
    # measure1 = models.CharField(max_length=50, blank=True)
    # measure2 = models.CharField(max_length=50, blank=True)
    # measure3 = models.CharField(max_length=50, blank=True)
    # measure4 = models.CharField(max_length=50, blank=True)
    # measure5 = models.CharField(max_length=50, blank=True)
    # measure6 = models.CharField(max_length=50, blank=True)
    # measure7 = models.CharField(max_length=50, blank=True)
    # measure8 = models.CharField(max_length=50, blank=True)
    # measure9 = models.CharField(max_length=50, blank=True)
    # measure10 = models.CharField(max_length=50, blank=True)
    # measure11 = models.CharField(max_length=50, blank=True)
    # measure12 = models.CharField(max_length=50, blank=True)
    # measure13 = models.CharField(max_length=50, blank=True)
    # measure14 = models.CharField(max_length=50, blank=True)
    # measure15 = models.CharField(max_length=50, blank=True)
    # measure16 = models.CharField(max_length=50, blank=True)
    # measure17 = models.CharField(max_length=50, blank=True)
    # measure18 = models.CharField(max_length=50, blank=True)
    # measure19 = models.CharField(max_length=50, blank=True)
    # measure20 = models.CharField(max_length=50, blank=True)
    # ingredient1 = models.CharField(max_length=50, blank=True)
    # ingredient2 = models.CharField(max_length=50, blank=True)
    # ingredient3 = models.CharField(max_length=50, blank=True)
    # ingredient4 = models.CharField(max_length=50, blank=True)
    # ingredient5 = models.CharField(max_length=50, blank=True)
    # ingredient6 = models.CharField(max_length=50, blank=True)
    # ingredient7 = models.CharField(max_length=50, blank=True)
    # ingredient8 = models.CharField(max_length=50, blank=True)
    # ingredient9 = models.CharField(max_length=50, blank=True)
    # ingredient10 = models.CharField(max_length=50, blank=True)
    # ingredient11 = models.CharField(max_length=50, blank=True)
    # ingredient12 = models.CharField(max_length=50, blank=True)
    # ingredient13 = models.CharField(max_length=50, blank=True)
    # ingredient14 = models.CharField(max_length=50, blank=True)
    # ingredient15 = models.CharField(max_length=50, blank=True)
    # ingredient16 = models.CharField(max_length=50, blank=True)
    # ingredient17 = models.CharField(max_length=50, blank=True)
    # ingredient18 = models.CharField(max_length=50, blank=True)
    # ingredient19 = models.CharField(max_length=50, blank=True)
    # ingredient20 = models.CharField(max_length=50, blank=True)
    # instructions = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)